// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6420.powerupcode.subsystems;

import org.usfirst.frc6420.powerupcode.RobotMap;
import org.usfirst.frc6420.powerupcode.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.sensors.PigeonIMU;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class DigitalInputs extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DigitalInput leftSelector = RobotMap.digitalInputsLeftSelector;
    private final DigitalInput centerSelector = RobotMap.digitalInputsCenterSelector;
    private final DigitalInput rightSelector = RobotMap.digitalInputsRightSelector;
    private final Encoder leftEncoder = RobotMap.digitalInputsLeftEncoder;
    private final Encoder rightEncoder = RobotMap.digitalInputsRightEncoder;
    private final PigeonIMU pigeonIMU1 = RobotMap.digitalInputsPigeonIMU1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
   // PigeonIMU pigeon1 = new PigeonIMU(1);

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    	
    	
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }
    
    public boolean leftSelectorOn() {
    	return leftSelector.get();
    }
    public boolean centerSelectorOn() {
    	return centerSelector.get();
    }
    public boolean rightSelectorOn() {
    	return rightSelector.get();
    }

    public double getAverageEncoderCount()
    {
    	return (rightEncoder.get() + leftEncoder.get()) *0.5;
    }
    
    public double getAngle() {
    	   	
    	double [] ypr = new double[3]; 

    //	pigeon1.getYawPitchRoll(ypr);
    	pigeonIMU1.getYawPitchRoll(ypr);
    	    	
    	return ypr[0];
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

