// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6420.powerupcode.commands;
//import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc6420.powerupcode.Constants;
import org.usfirst.frc6420.powerupcode.Robot;
//import org.usfirst.frc6420.powerupcode.RobotMap;
//import org.usfirst.frc6420.powerupcode.subsystems.DriveBase;
import org.usfirst.frc6420.powerupcode.subsystems.DigitalInputs;
/**
 *
 */
public class AutoMove extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	private double speed = Constants.autoForwardSpeed;
	private double absolute_target;
	private double encoderCounts;
	//private DriveBase drivebase = Robot.driveBase;
	private DigitalInputs digitalinputs = Robot.digitalInputs;
	

	
    public AutoMove(int encoderCounts) {
    	this.encoderCounts = encoderCounts;
    	System.out.println("inside of AutoMove");
    	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    
    public AutoMove(int encoderCounts, int speed) {
    	this.encoderCounts = encoderCounts;
    	this.speed = speed;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
            // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

            // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
            // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        }


    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	this.absolute_target = digitalinputs.getAverageEncoderCount() + encoderCounts;
    	
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	if (encoderCounts > 0){
    		Robot.driveBase.setMotorSpeeds(-this.speed, -this.speed);
    	}else{
    		Robot.driveBase.setMotorSpeeds(this.speed, this.speed);
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        if ( encoderCounts > 0){
        	return digitalinputs.getAverageEncoderCount() > this.absolute_target - 15.4 * this.speed;
        }else{
        	return digitalinputs.getAverageEncoderCount() < this.absolute_target + 15.4 * this.speed;
        }
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	Robot.driveBase.setMotorSpeeds(0, 0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
