// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6420.powerupcode.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
//import org.usfirst.frc6420.powerupcode.subsystems.*;

/**
 *
 */
public class robotPosRightSwitch extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public robotPosRightSwitch() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

    	addSequential (new AutoMove(100));
    	
    	addSequential (new AutoTurn(-90));
    	
    	//addSequential (new AutoLift(1));
    	
    	//addSequential (new AutoMove(100));
    	
    	//addSequential (new AutoGrabber(1));
    	
    	//addSequential (new AutoMove(-100));
    	
    	//addSequential (new AutoLift(1));
    } 
}
