// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6420.powerupcode;

import org.usfirst.frc6420.powerupcode.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

import org.usfirst.frc6420.powerupcode.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton button1;
    public JoystickButton button2;
    public JoystickButton button3;
    public JoystickButton button4;
    public JoystickButton button9;
    public JoystickButton button11;
    public JoystickButton button7;
    public JoystickButton button8;
    public Joystick joystick1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        joystick1 = new Joystick(0);
        
        button8 = new JoystickButton(joystick1, 8);
        button8.whileHeld(new LiftUp());
        button7 = new JoystickButton(joystick1, 7);
        button7.whileHeld(new LiftDown());
        button11 = new JoystickButton(joystick1, 11);
        button11.whenPressed(new TimedGrabberIn());
        button9 = new JoystickButton(joystick1, 9);
        button9.whenPressed(new TimedGrabberOut());
        button4 = new JoystickButton(joystick1, 4);
        button4.whileHeld(new LiftUp());
        button3 = new JoystickButton(joystick1, 3);
        button3.whileHeld(new LiftDown());
        button2 = new JoystickButton(joystick1, 2);
        button2.whileHeld(new GrabberIn());
        button1 = new JoystickButton(joystick1, 1);
        button1.whileHeld(new GrabberOut());


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("TeleOpDrive", new TeleOpDrive());
        SmartDashboard.putData("LiftUp", new LiftUp());
        SmartDashboard.putData("LiftDown", new LiftDown());
        SmartDashboard.putData("GrabberIn", new GrabberIn());
        SmartDashboard.putData("GrabberOut", new GrabberOut());
        SmartDashboard.putData("TimedGrabberIn", new TimedGrabberIn());
        SmartDashboard.putData("TimedGrabberOut", new TimedGrabberOut());
        SmartDashboard.putData("AutoLeft", new AutoLeft());
        SmartDashboard.putData("AutoCenter", new AutoCenter());
        SmartDashboard.putData("AutoRight", new AutoRight());
        SmartDashboard.putData("AutoMove", new AutoMove());
        SmartDashboard.putData("AutoTurn", new AutoTurn());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick1() {
        return joystick1;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

